### ISSUE TITLE
typos + broken link

### ISSUE THREAD

**Issue by donhuvy** [spring-guides/gs-register-twitter-app#5]
**(1)** 
<img width="708" alt="screen shot 2017-05-06 at 22 31 35" src="https://cloud.githubusercontent.com/assets/1328316/25773668/ce3caf60-32ab-11e7-883c-27b86b0aaed3.png">

**(2)** Broken link
<img width="703" alt="screen shot 2017-05-06 at 22 32 22" src="https://cloud.githubusercontent.com/assets/1328316/25773677/efa3d55c-32ab-11e7-881f-37377847d3f1.png">

**(3)** Text on icon/background
<img width="286" alt="screen shot 2017-05-06 at 22 30 46" src="https://cloud.githubusercontent.com/assets/1328316/25773664/b37d19bc-32ab-11e7-9ffa-f062d3fda91c.png">

**(4)** Content
At this step:

> Now you can use your consumer key and secret to access Twitter’s API. The sample utility application in GitHub is an example of an application that can use the consumer key and secret to search Twitter.

I don't know how to continue, what is its mean.

**Comment by gregturn** [comment]
Based on https://spring.io/blog/2018/07/03/spring-social-end-of-life-announcement, this guide is no longer supported.
